# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_travel_travelmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travelManager',
        ),
    ]
