# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_travelmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='join',
        ),
        migrations.AddField(
            model_name='travel',
            name='joiner',
            field=models.ManyToManyField(related_name='join_travels', to='main.User'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_travel', to='main.User'),
        ),
    ]
