# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180302_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='main.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='travel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='joiner',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
