# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180305_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
